### PR TITLE
adjust font & size for pgp-key-input

### PR DESCRIPTION
**Pull request by trashcan55**
should do #261

A little unsure what would be the best way to set the width for the input box. adding a minimum width to the app.css file makes the boxes overlap, so i changed the relative column width instead.

### CODE REVIEW

**Comment by trashcan55** [comment]
learning git is fun :expressionless:  
https://github.com/systemli/userli/pull/265/commits/212e941579ad648aa4bcfbb240670fddf6424108 was not actually meant to be commited of course..

**Comment by t2d** [comment]
Thank you for sending you first pull request here. Please clean up this branch before further review.
If you don't want 212e94, I think you have to do:
```
git revert 212e941
git rebase -i HEAD~5
git push --force
```

**Comment by trashcan55** [comment]
i did a little correction and cleaned up (again..), hope it's alright now

**Comment by t2d** [comment]
Thank you, it looks much better than before!

**Pull request merged**
