### PR TITLE
Migrate Doctrine Entity/DB mapping to PHP annotations

### PR DESCRIPTION
**Pull request by doobry-systemli**
This is in preparation of migrating the mapping to PHP attributes as soon as we raise the minimum PHP version to 8.0 or higher.

### CODE REVIEW

**Review by t2d — APPROVED** [review]
I tested this branch in Vagrant and couldn't see any problems

**Review by 0x46616c6b — CHANGES_REQUESTED** [review]
I am not sure but it seems not right to put the Annotations in Traits 🤔

**Comment by doobry-systemli** [comment]
> I am not sure but it seems not right to put the Annotations in Traits 🤔

Why not? Using these annotations (or later attributes) just above the variable definitions is how doctrine reads its properties. At least that's how I understood it from the documentation. And given that we use traits to define some of our properties and their getters/setters, that's the only place where the annotations can live, no?

**Comment by 0x46616c6b** [comment]
> > I am not sure but it seems not right to put the Annotations in Traits 🤔
> 
> Why not? Using these annotations (or later attributes) just above the variable definitions is how doctrine reads its properties. At least that's how I understood it from the documentation. And given that we use traits to define some of our properties and their getters/setters, that's the only place where the annotations can live, no?

For me, a Trait should be as simple as possible. But maybe it is a pragmatic approach, and we may not share these Traits anyway.

**Review by 0x46616c6b — APPROVED** [review]

**Pull request merged**
