### PR TITLE
Change input type to make css work

### PR DESCRIPTION
**Pull request by 1resu**
The css file uses `.form-signin input[type="email"]` - [app.css](https://github.com/systemli/userli/blob/57cbe34a7bcb3f00324977a4f45b299c3562b631/assets/css/app.css#L35)

### CODE REVIEW

**Comment by doobry-systemli** [comment]
Can you elaborate on what you try to achieve here? Seems legit to change the input type to `email`, but I'd like to understand what's going to be fixed with this change.

Also, if you change the input field type in the login form on login page, it should be changed in the login form on startpage accordingly.

**Comment by 1resu** [comment]
> Can you elaborate on what you try to achieve here?

Please have a look at [this](https://users.systemli.org/de/login) page. The space between doesn't look right. And also the non-rounded corners of the password field. There is not css style for an input field of the type "text".

I assumed you mistakenly choosed the type of the input field. With this commit the form fields at /login look much nicer.

**Comment by doobry-systemli** [comment]
I see, thanks a lot for the explanation. In my browsers, the visual changes are marginal, but I agree that 'email' is the correct input field type here :blush:

**Comment by t2d** [comment]
This result in users now being required to enter full email addresses, not only localpart. I think it's not super critical, but I think it wasn't intended

**Pull request merged**
